name: Trigger Downstream Workflows

on:
  # 自动触发：每天早上6点 UTC 时间 (即北京时间 0:00)
  # 如果您的意图是北京时间早上 6 点，cron 应为 '0 22 * * *' (即 UTC 14:00)
  schedule:
    - cron: '0 22 * * *'
  # 手动触发
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Job 1: 并行调用 zn-m2-oc.yml
  call-zn-m2-oc:
    # 关键：直接在 job 级别使用 'uses' 关键字调用其他工作流
    uses: ./.github/workflows/zn-m2-oc.yml 
    # runs-on 不需要指定，因为它会继承被调用工作流的设置

  # Job 2: 并行调用 zn-m2-pw.yml
  call-zn-m2-pw:
    # 关键：另一个 job 调用另一个工作流
    # 由于没有 'needs' 依赖关系，Job 1 和 Job 2 会自动并行运行
    uses: ./.github/workflows/zn-m2-pw.yml