name: Auto-Clean

on:
  #自动清理：每天早上6点 (UTC time, which is 0 22 * * * CST)
  schedule:
    - cron: '0 22 * * *'
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0

  # --- 新增任务：运行其他工作流 ---
  run_other_workflows:
    runs-on: ubuntu-latest
    needs: auto_clean # 确保在清理任务完成后运行
    steps:
      - name: Run zn-m2-oc.yml workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'zn-m2-oc.yml', # 要触发的工作流文件名
              ref: context.ref, # 使用当前分支，通常是 main 或 master
              // 如果 zn-m2-oc.yml 需要输入参数，可以在此添加
              // inputs: {
              //   key: 'value'
              // }
            });
            console.log('Successfully dispatched zn-m2-oc.yml');

      - name: Run zn-m2-pw.yml workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'zn-m2-pw.yml', # 要触发的工作流文件名
              ref: context.ref, # 使用当前分支，通常是 main 或 master
              // 如果 zn-m2-pw.yml 需要输入参数，可以在此添加
              // inputs: {
              //   key: 'value'
              // }
            });
            console.log('Successfully dispatched zn-m2-pw.yml');
